name: Source Distribution
inputs:
  ghc:
    description: GHC Version
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses:
        actions/setup-node@v3
        # echo "$PWD/cli" >> $GITHUB_PATH
        # echo "export PATH=\$PATH:$PWD/cli" >> $GITHUB_ENV
    - name: Download HConf
      shell: bash
      run: |
        npm i
        npm run hconf
        mkdir /home/runner/.local/bin
        mv ./cli/hconf /home/runner/.local/bin/hconf
        hconf setup ${{ inputs.ghc }}

    - name: HConf Haskell
      uses: haskell/actions/setup@v1.2
      with:
        ghc-version: ${{ inputs.ghc }}
        enable-stack: true

    - name: Cache Stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os  }}-${{ inputs.ghc }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.ghc }}-stack
