name: Source Distribution
inputs:
  ghc:
    description: GHC Version
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Install/Setup HConf
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/nalchevanidze/hconf/main/scripts/install.sh | sh -s .
        hconf setup ${{ inputs.ghc }}

    - uses: actions/setup-node@v3

    - name: Install NPM
      shell: bash
      run: npm i

    - name: HConf Haskell
      uses: haskell/actions/setup@v2.9.0
      with:
        ghc-version: ${{ inputs.ghc }}
        enable-stack: true

    - name: Cache Stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os  }}-${{ inputs.ghc }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.ghc }}-stack
