name: Source Distribution
inputs:
  ghc:
    description: GHC Version
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Setup Haskell
      uses: haskell/actions/setup@v1.2
      with:
        ghc-version: ${{ inputs.ghc }}
        enable-stack: true

    - name: Setup Haskell
      uses: haskell/actions/setup@v1.2
      with:
        ghc-version: ${{ inputs.ghc }}
        enable-stack: true

    - name: Cache Stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os  }}-${{ inputs.ghc }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.ghc }}-stack
