enum TestEnum {
  EnumA
  EnumB
}

input Input1 {
  field1: ID = 1
  field2: String = "some text"
  field3: TestEnum = EnumB
}

input Input2 {
  field1: Input1
  field2: String
}

type Query {
  field(
    i1: Input2 = { field1: { field2: 1 }, field2: true }
    i2: Input1 = { field1: { field3: 2344 }, field2: 123 }
    i3: TestEnum = EnumBB
    i4: ID = true
    i5: Int = "some text"
  ): Int
}
