name: morpheus-graphql-subscriptions
version: 0.17.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql, subscriptions
synopsis: Morpheus GraphQL Subscriptions
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!

extra-source-files:
  - changelog.md
  - README.md

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - aeson                 >= 1.4.4.0   && <= 1.6
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - morpheus-graphql-core >= 0.17.0    && <  0.18.0
  - transformers          >= 0.3.0.0   && <  1.0
  - mtl                   >= 2.0       && <= 3.0
  - relude                >= 0.3.0
  - websockets            >= 0.11.0    && <= 1.0
  - uuid                  >= 1.0       && <= 1.4
  - unliftio-core         >= 0.0.1     && <= 0.4
  - morpheus-graphql-app  >= 0.17.0    && <= 0.18.0

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.Subscriptions
    - Data.Morpheus.Subscriptions.Internal
  ghc-options: -Wall

tests:
  morpheus-subscription-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - tasty
      - tasty-hunit
      - aeson
      - directory >= 1.0
