name: morpheus-graphql-benchmarks
version: 0.28.3
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: Morpheus GraphQL Benchmarks
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
license-file: LICENSE
description: Build GraphQL APIs with your favorite functional language!
extra-source-files:
- README.md
data-files:
- samples/**/*.gql
dependencies:
- base                   >=  4.7.0   &&  <  5.0.0
- bytestring             >=  0.10.4  &&  <  1.0.0
- criterion              >=  1.0     &&  <  2.0.0
- graphql                >=  0.5     &&  <  2.0.0
- megaparsec             >=  7.0.0   &&  <  10.0.0
- morpheus-graphql-core  >=  0.28.0  &&  <  0.29.0
- relude                 >=  0.3.0   &&  <  2.0.0
- text                   >=  1.2.3   &&  <  3.0.0
- unordered-containers   >=  0.2.8   &&  <  1.0.0
benchmarks:
  morpheus-graphql-bench:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -eventlog
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N6
