name: morpheus-graphql-code-gen
version: 0.18.0
github: "morpheusgraphql/morpheus-graphql"
license: BSD3
author: "Daviti Nalchevanidze"
category: web, graphql, cli
synopsis: Morpheus GraphQL CLI
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"

description: code generator for Morpheus GraphQL

extra-source-files:
  - changelog.md
  - README.md

dependencies:
  - base                  >= 4.7       && <  5
  - morpheus-graphql-core >= 0.18.0    && <  0.19.0
  - text                  >= 1.2.3.0   && <  1.3
  - bytestring            >= 0.10.4    && <  0.11
  - prettyprinter         >= 1.2       && <  2.0
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - containers            >=0.4.2.1    && <  0.7
  - relude                >= 0.3.0     && <  1.1
  - template-haskell      >= 2.0       && <  3.0

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.CodeGen.Internal.AST
    - Data.Morpheus.CodeGen
    - Data.Morpheus.CodeGen.Internal.TH
  ghc-options: -Wall

executables:
  morpheus:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
      - morpheus-graphql-code-gen
      - optparse-applicative  >= 0.12      && <  0.17
      - filepath              >= 1.1       && <  1.5
