name: morpheus-graphql-code-gen
version: 0.19.2
github: morpheusgraphql/morpheus-graphql
license: BSD3
author: Daviti Nalchevanidze
category: web, graphql, cli
synopsis: Morpheus GraphQL CLI
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
description: code generator for Morpheus GraphQL
extra-source-files:
  - README.md
  - changelog.md
dependencies:
  - base                   >=  4.7      &&  <  5
  - bytestring             >=  0.10.4   &&  <  0.11
  - containers             >=  0.4.2.1  &&  <  0.7
  - morpheus-graphql-core  >=  0.19.0   &&  <  0.20.0
  - prettyprinter          >=  1.2      &&  <  2.0
  - relude                 >=  0.3.0    &&  <  2.0
  - text                   >=  1.2.3.0  &&  <  1.3
  - template-haskell       >=  2.0      &&  <  3.0
  - unordered-containers   >=  0.2.8.0  &&  <  0.3
library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.CodeGen
    - Data.Morpheus.CodeGen.Internal.AST
    - Data.Morpheus.CodeGen.Internal.TH
  ghc-options: '-Wall'
executables:
  morpheus:
    main: Main.hs
    source-dirs: app
    ghc-options: '-Wall'
    dependencies:
      - filepath                   >=  1.1   &&  <  1.5
      - morpheus-graphql-code-gen
      - optparse-applicative       >=  0.12  &&  <  0.18
