name: morpheus-graphql-code-gen-utils
version: 0.22.0
github: morpheusgraphql/morpheus-graphql
license: BSD3
author: Daviti Nalchevanidze
category: web, graphql, cli
synopsis: Morpheus GraphQL CLI
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
description: code generator for Morpheus GraphQL
extra-source-files:
  - README.md
  - changelog.md
dependencies:
  - base                   >=  4.7.0    &&  <  5.0.0
  - bytestring             >=  0.10.4   &&  <  0.12.0
  - containers             >=  0.4.2.1  &&  <  0.7.0
  - morpheus-graphql-core  >=  0.22.0   &&  <  0.23.0
  - prettyprinter          >=  1.7.0    &&  <  2.0.0
  - relude                 >=  0.3.0    &&  <  2.0.0
  - text                   >=  1.2.3    &&  <  1.3.0
  - template-haskell       >=  2.0.0    &&  <  3.0.0
  - unordered-containers   >=  0.2.8    &&  <  0.3.0
library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.CodeGen.Internal.AST
    - Data.Morpheus.CodeGen.Printer
    - Data.Morpheus.CodeGen.TH
    - Data.Morpheus.CodeGen.Utils
  ghc-options: '-Wall'
