name: morpheus-graphql-code-gen-utils
version: 0.28.3
github: morpheusgraphql/morpheus-graphql
license: BSD3
author: Daviti Nalchevanidze
category: web, graphql, cli
synopsis: Morpheus GraphQL CLI
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
description: code generator for Morpheus GraphQL
extra-source-files:
- README.md
- changelog.md
dependencies:
- base                   >=  4.7.0    &&  <  5.0.0
- bytestring             >=  0.10.4   &&  <  1.0.0
- containers             >=  0.4.2.1  &&  <  1.0.0
- morpheus-graphql-core  >=  0.28.0   &&  <  0.29.0
- mtl                    >=  2.0.0    &&  <  3.0.0
- prettyprinter          >=  1.7.0    &&  <  2.0.0
- relude                 >=  0.3.0    &&  <  2.0.0
- template-haskell       >=  2.0.0    &&  <  3.0.0
- text                   >=  1.2.3    &&  <  3.0.0
- unordered-containers   >=  0.2.8    &&  <  1.0.0
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Data.Morpheus.CodeGen.Internal.AST
  - Data.Morpheus.CodeGen.Printer
  - Data.Morpheus.CodeGen.TH
  - Data.Morpheus.CodeGen.Utils
