directive @TestDirective(name: String!, enum: TestEnum) INPUT_OBJECT| OBJECT

scalar  TestScalar @TestDirective(name: "SomeName")

enum  TestEnum @TestDirective(name: "SomeName") {
  EnumA
  EnumB
  EnumC
}

input  Coordinates @TestDirective(name: "SomeName") {
  latitude: TestScalar!
  longitude: Int!
}

type  Address {
  street: [[[[String!]!]!]]
  score: Float!
}

type  User {
  type: String!
  address(coordinates: Coordinates!, type: String): Int!
  friend(id: ID!, cityID: TestEnum): User!
}

union  TestUnion @TestDirective(name: "SomeName") = User | Address

type  MyQuery {
  user: User!
  testUnion: TestUnion
}

type  MyMutation {
  newUser: User!
}

schema {
  query: MyQuery
  mutation: MyMutation
}