type Query {
  deity(name: String!): Deity!
}

type Mutation {
  createDeity(name: String!, power: String): Deity!
}

"""
Description for Deity
"""
type Deity {
  """
  Description for name
  """
  name: String!
  power: String @deprecated(reason: "some reason for")
}