query {
  character {
    ... on Character {
      __typename
      name
    }
    ... on Deity {
      __typename
      name
    }
    ... on Hero {
      __typename
      name
      hobby
    }
  }
}
