name: morpheus-graphql-example
version: 0.0.1
github: "nalchevanidze/morpheus-graphql"
license: BSD3
author: "Daviti Nalchevanidze"
maintainer: "d.nalchevanidze@gmail.com"
copyright: "2019 Daviti Nalchevanidze"
category: example, web, graphql
synopsis: Morpheus GraphQL

description: Example usage of Morpheus GraphQL

dependencies:
  - base >= 4.7 && < 5
  - morpheus-graphql
  - scotty
  - aeson
  - bytestring
  - mtl
  - text

executables:
  api:
    main: Main.hs
    source-dirs: src
    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
      -Wall
    dependencies:
      - morpheus-graphql
