directive @DirectiveA(a1: Int!) on SCALAR

directive @DirectiveB(a1: MyInput!) on INPUT_FIELD_DEFINITION

input MyInput {
  field: String
}

scalar MyScalar @DirectiveA(a1: 0.1)
scalar MyScalar2 @DirectiveA(a1: "some string")
scalar MyScalar3 @DirectiveA(a1: True)

enum TestEnum {
  EnumA @deprecated(reason: EnumA)
  EnumB @deprecated(reason: 1)
  EnumB @deprecated(reason: Bool)
}

input Input {
  field1: ID @DirectiveB(a1: { field: 2394 })
  field2: String @DirectiveB(a1: ["some deprication"])
}

type Query {
  field: Int
}
