enum TestEnum {
  EnumA
  EnumB
  EnumC
}

input InputSimple {
  inputField1: ID!
}

input InputCompound {
  inputField2: String! = "some value"
  inputField3: [InputSimple]! = [{}]
  inputField4: [InputSimple]! = [{ inputField1: "some input" }]
}

type User implements Person {
  name: String!
  address(input: Coordinates!, comment: String): String!
}

input TypeInput {
  data: String!
}

type Query {
  user: User!
}
