query GetCharacters {
  character {
    name
    ... on Deity {
      power
    }

    ... on Hero {
      hobby
    }
  }
  anonymous: character {
    name1: name
    name
  }
  heros: character {
    ... on Hero {
      hobby
    }
    ... on Character {
      name2: name
    }
  }
  superheros: character {
    ... on Hero {
      hobby
    }
  }
}
