query GetCharacters {
  character {
    name
    ...DEITY
    ...HERO
  }
  anonymous: character {
    name1: name
    name
  }
  heros: character {
    ...HERO
    ... on Character {
      name2: name
    }
  }
  superheros: character {
    ...HERO
  }
}

fragment DEITY on Deity {
  power
}

fragment HERO on Hero {
  __typename
  hobby
}