enum TestEnum {
  EnumA
  EnumB
  EnumC
}

input InputSimple {
  field1: ID = EnumA
  field2: String = EnumA
  field3: TestEnum = UnknownEnum
  field4: TestEnum = 1
  field5: TestEnum = "string"
}

type Query {
  field1(input: InputSimple): Int
}
