import Document, { Html, Head, Main, NextScript } from "next/document";
import Link from "next/link";
import { useContext } from "react";
import { NavContext, NavContextProvider } from "../components/nav-context";
import Header from "../components/header";

const NavLink = ({ to, children, level }) => (
  <Link
    to={`${window.location.pathname}#${to}`}
    style={{
      color: "rgb(39, 51, 63)",
      textDecoration: "none",
      padding: "0.1rem 0rem",
      paddingLeft: (level - 1) * 16,
      fontSize: 8 + 20 / (level + 1),
    }}
  >
    {children}
  </Link>
);

const Navigation = () => {
  const [items] = useContext(NavContext);
  return (
    <nav
      style={{
        gridColumn: "1 / 3",
        display: "flex",
        paddingBottom: 5,
        flexDirection: "column",
        position: "sticky",
        top: "5vh",
        height: "80vh",
      }}
    >
      {items.map(({ id, children, level }) => (
        <NavLink to={id} key={id} level={level}>
          {children}
        </NavLink>
      ))}
    </nav>
  );
};

const Layout = ({ children, ...props }) => (
  <NavContextProvider value={[]}>
    <Header siteTitle={props.title} />
    <div
      style={{
        width: "100%",
        background: "rgb(215 239 253 / 65%)",
      }}
    >
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(12, 1fr)",
          gap: "2em",
          maxWidth: 1260,
          margin: "0 auto",
          padding: "8rem 2rem",
          background: "rgb(243 251 255 / 81%)",
          border: "2px solid white",
          borderRadius: 5,
        }}
      >
        {<Navigation />}
        <div
          style={{
            gridColumn: "3 / 13",
          }}
        >
          {children}
        </div>
      </div>
    </div>
  </NavContextProvider>
);

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <link
            rel="stylesheet"
            href="https://unpkg.com/dracula-prism/dist/css/dracula-prism.css"
          ></link>
          <meta name="description" content="Generated by create next app" />
          <meta name="keywords" content="Morpheus GraphQL, GraphQL, Haskell" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <body>
          <Layout>
            <Main />
          </Layout>
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
