- ignore:
    {
      name: Unused LANGUAGE pragma,
      within:
        [
          Client.Queries.GetUsers,
          Client.Queries.GetPosts,
          Client.Blog,
          Server.Blog,
        ],
    }
- ignore: { name: Use camelCase, within: [Namespaces.Cases] }
