language: c
sudo: false

cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

matrix:
  include:
#    - env: GHCVER=ghc-8.2.2 STACK_YAML=stack-11.10.yaml
#      addons:
#        apt:
#          sources:
#          - hvr-ghc
#          packages:
#          - ghc-8.2.2
    - env: GHCVER=8.4.3 STACK_YAML=stack.yaml
      addons:
        apt:
          sources:
          - hvr-ghc
          packages:
          - ghc-8.4.3
    - env: GHCVER=8.6.4 STACK_YAML=stack-13.15.yaml
          addons:
            apt:
              sources:
              - hvr-ghc
              packages:
              - ghc-8.6.4
    - env: GHCVER=8.6.5 STACK_YAML=stack-13.24.yaml
      addons:
        apt:
          sources:
          - hvr-ghc
          packages:
          - ghc-8.6.5

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot

script:
- stack --no-terminal test --haddock --no-haddock-deps
