name: morpheus-graphql
version: 0.17.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!

extra-source-files:
  - changelog.md
  - README.md

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                            >= 4.7           && <  5
  - bytestring                      >= 0.10.4        && <  0.11
  - text                            >= 1.2.3.0       && <  1.3
  - aeson                           >= 1.4.4.0       && <= 1.6
  - containers                      >= 0.4.2.1       && <  0.7
  - unordered-containers            >= 0.2.8.0       && <  0.3
  - transformers                    >= 0.3.0.0       && <  0.6
  - vector                          >= 0.12.0.1      && <  0.13
  - mtl                             >= 2.0           && <= 3.0
  - morpheus-graphql-code-gen       >= 0.17.0        && <  0.18.0
  - morpheus-graphql-core           >= 0.17.0        && <  0.18.0
  - morpheus-graphql-app            >= 0.17.0        && <  0.18.0
  - template-haskell                >= 2.0           && <= 3.0
  - relude                          >= 0.3.0

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus
    - Data.Morpheus.Kind
    - Data.Morpheus.Types
    - Data.Morpheus.NamedResolvers
    - Data.Morpheus.Server
    - Data.Morpheus.Document
  ghc-options: -Wall

tests:
  morpheus-graphql-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - morpheus-graphql-tests          >= 0.17.0        && <  0.18.0
      - morpheus-graphql                >= 0.17.0        && <  0.18.0
      - morpheus-graphql-subscriptions  >= 0.17.0        && <  0.18.0
      - tasty
      - tasty-hunit
      - aeson
