name: morpheus-graphql
version: 0.12.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!

extra-source-files:
  - changelog.md
  - README.md

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - megaparsec            >= 7.0.0     && <  9.0.0
  - aeson                 >= 1.4.4.0   && <= 1.6
  - containers            >= 0.4.2.1   && <  0.7
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - transformers          >= 0.3.0.0   && <  0.6
  - scientific            >= 0.3.6.2   && <  0.4
  - vector                >= 0.12.0.1  && <  0.13
  - mtl                   >= 2.0       && <= 3.0
  - morpheus-graphql-core >= 0.12.0

  - uuid                  >= 1.0       && <= 1.4
  - websockets            >= 0.11.0    && <= 1.0
  - template-haskell      >= 2.0       && <= 3.0
  - unliftio-core         >= 0.0.1     && <= 0.4

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus
    - Data.Morpheus.Kind
    - Data.Morpheus.Types
    - Data.Morpheus.Server
    - Data.Morpheus.Document
    - Data.Morpheus.Types.Internal.Subscription
    - Data.Morpheus.Types.Directive
  ghc-options: -Wall

tests:
  morpheus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - morpheus-graphql
      - tasty
      - tasty-hunit
      - aeson
