name: morpheus-graphql
version: 0.1.1
github: "nalchevanidze/morpheus-graphql"
license: BSD3
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: "d.nalchevanidze@gmail.com"
copyright: "(c) 2019 Daviti Nalchevanidze"

description: Build GraphQL APIs with your favourite functional language!

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                  >= 4.7       && <  5
  - megaparsec            >= 7.0.0     && <  8.0
  - aeson                 >= 1.0       && <= 1.5
  - attoparsec            >= 0.13.2    && <  0.14
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - containers            >= 0.4.2.1   && <  0.7
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - transformers          >= 0.3.0.0   && <  0.6
  - scientific            >= 0.3.6.2   && <  0.4
  - vector                >= 0.12.0.1  && <  0.13
  - mtl                   >= 2.0       && <= 2.2.2
  - websockets            >= 0.11.0    && <= 0.12.5.3
  - wai-websockets        >= 1.0       && <= 3.5
  - utf8-string           >= 1.0.1     && <  1.1
  - uuid                  >= 1.0       && <= 1.4
  - template-haskell
  - lens

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus
    - Data.Morpheus.Kind
    - Data.Morpheus.Types
    - Data.Morpheus.Server
    - Data.Morpheus.Document
    - Data.Morpheus.Client
    - Data.Morpheus.Parsing.JSONSchema.Parse
  ghc-options: -Wall

tests:
  morpheus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - morpheus-graphql
      - tasty
      - tasty-hunit
      - aeson

executables:
  morpheus:
    main: Main.hs
    source-dirs: CLI
    ghc-options: -threaded
      -rtsopts
      -with-rtsopts=-N
      -Wall
    dependencies:
      - base >= 4.7 && < 5
      - morpheus-graphql
      - aeson
      - bytestring
      - mtl
      - text
      - optparse-applicative  >= 0.12      && < 0.15
      - filepath              >= 1.1       && < 1.5
  api:
    main: Main.hs
    source-dirs: examples
    ghc-options: -threaded
      -rtsopts
      -with-rtsopts=-N
      -Wall
    dependencies:
      - base >= 4.7 && < 5
      - morpheus-graphql
      - scotty
      - aeson
      - bytestring
      - mtl
      - text
      - wai
      - warp
