# 8.10.1
resolver: nightly-2020-06-29
packages:
  - morpheus-graphql-examples-scotty
  - morpheus-graphql-examples-servant
  - morpheus-graphql-examples-client
  - morpheus-graphql-client
  - morpheus-graphql-core
  - .

allow-newer: true
extra-deps:
  - servant-server-0.16.2
  - servant-0.16.2
