# 9.0.1
resolver: nightly-2021-09-12
save-hackage-creds: false
packages:
  - morpheus-graphql-benchmarks
  - morpheus-graphql-examples-scotty
  - morpheus-graphql-examples-servant
  - morpheus-graphql-examples-client
  - morpheus-graphql-examples-code-gen
  - morpheus-graphql-subscriptions
  - morpheus-graphql-client
  - morpheus-graphql-core
  - morpheus-graphql-app
  - morpheus-graphql-tests
  - morpheus-graphql-code-gen
  - .

extra-deps:
  - graphql-1.0.0.0@sha256:1f63fbc380984d4d501bbc8c945658b042b98ccba6f66bdf07d4417a560f3ee4,3392
  - megaparsec-9.0.1@sha256:2244ab77521a52a0083966c5405b3151f149e1db50b1a5b104cd9b1e56617203,3248
