resolver: lts-22.30
packages:
- examples/yesod-pubsub
- examples/servant
- examples/code-gen-docs
- examples/scotty
- examples/code-gen
- examples/client
- helpers/benchmarks
- morpheus-graphql-app
- morpheus-graphql-code-gen-utils
- morpheus-graphql-server
- morpheus-graphql-tests
- morpheus-graphql-core
- morpheus-graphql-subscriptions
- morpheus-graphql-code-gen
- morpheus-graphql-client
- morpheus-graphql
save-hackage-creds: false
extra-deps:
- attoparsec-aeson-2.1.0.0
- dependent-map-0.2.4.0
- dependent-sum-0.4
