# 8.10.1
resolver: nightly-2021-03-29
save-hackage-creds: false
packages:
  - morpheus-graphql-benchmarks
  - morpheus-graphql-examples-scotty
  - morpheus-graphql-examples-servant
  - morpheus-graphql-examples-client
  - morpheus-graphql-subscriptions
  - morpheus-graphql-client
  - morpheus-graphql-core
  - morpheus-graphql-app
  - morpheus-graphql-tests
  - morpheus-graphql-cli
  - .

extra-deps:
  - fraxl-0.3.0.0
  - haxl-2.3.0.0
  - dependent-map-0.2.4.0
  - dependent-sum-0.4
  - fastsum-0.1.1.1
  - type-aligned-0.9.6
  - graphql-0.11.0.0
