resolver: lts-19.28
save-hackage-creds: false
packages:
  - examples/client
  - examples/code-gen
  - examples/code-gen-docs
  - examples/scotty
  - examples/scotty-haxl
  - examples/scotty-freer-simple
  - examples/servant
  - examples/yesod-pubsub
  - morpheus-graphql-tests
  - morpheus-graphql-core
  - morpheus-graphql-code-gen-utils
  - morpheus-graphql-code-gen
  - morpheus-graphql-app
  - morpheus-graphql-client
  - morpheus-graphql-subscriptions
  - morpheus-graphql-server
  - morpheus-graphql
extra-deps:
  - dependent-map-0.2.4.0
  - dependent-sum-0.4
  - fraxl-0.3.0.0
  - haxl-2.4.0.0
  - type-aligned-0.9.6
