resolver: nightly-2025-12-21
packages:
- examples/client
- examples/code-gen
- examples/code-gen-docs
- examples/scotty
- examples/servant
- examples/yesod-pubsub
- morpheus-graphql-tests
- morpheus-graphql-core
- morpheus-graphql-code-gen-utils
- morpheus-graphql-code-gen
- morpheus-graphql-app
- morpheus-graphql-client
- morpheus-graphql-subscriptions
- morpheus-graphql-server
- morpheus-graphql-benchmarks
- morpheus-graphql
allow-newer: true
save-hackage-creds: false
extra-deps:
- fastsum-0.1.1.1
- fraxl-0.3.0.0
- haxl-2.5.1.1
- type-aligned-0.9.6
