resolver: nightly-2024-05-29
packages:
- examples/client
- examples/code-gen
- examples/code-gen-docs
- examples/scotty
- examples/scotty-fraxl
- examples/scotty-haxl
- examples/scotty-freer-simple
- examples/servant
- examples/yesod-pubsub
- morpheus-graphql-tests
- morpheus-graphql-core
- morpheus-graphql-code-gen-utils
- morpheus-graphql-code-gen
- morpheus-graphql-app
- morpheus-graphql-client
- morpheus-graphql-subscriptions
- morpheus-graphql-server
- morpheus-graphql-benchmarks
- morpheus-graphql
- hconf
allow-newer: true
save-hackage-creds: false
extra-deps:
- fraxl-0.3.0.0
- haxl-2.4.0.0
- type-aligned-0.9.6
