input Input1 {
  field: Int!
}

input Input2 {
  field: Input1!
  field2: Int!
  field3: Int
  field4: Int! = 123
}

input Input3 {
  field: Input2!
}

type Query {
  field(
    i1: Input3 = { field: {} }
    i2: Input3 = {}
    i3: Input3 = { field: { field: {} } }
  ): Int
}
