scalar MyScalar @deprecated

enum TestEnum @deprecated {
  EnumA @if
  EnumB
}

input Input1 @deprecated {
  field1: ID @if
  field2: String
}

type Query @deprecated {
  field(a1: Int @skip): Int @if
}
