scalar MyScalar @DirectveA

enum TestEnum @DirectveB {
  EnumA @DirectveB
  EnumB
}
type A @DirectveC {
  name: String! @DirectveC
}

type B @DirectveC {
  name: String! @DirectveC
}

union MyUnion @DirectveD = A | B

input Input1 @DirectveE {
  field1: ID @DirectveE
  field2: String
}

type Query @DirectveF {
  field(a1: Int @DirectveF): Int @DirectveF
}
