name: morpheus-graphql-examples-client
version: 0.1.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: examples
copyright: "(c) 2019 Daviti Nalchevanidze"
description: examples of GraphQL APIs

dependencies:
  - base                    >= 4.7       && <  5
  - bytestring              >= 0.10.4    && <  0.11
  - text                    >= 1.2.3.0   && <  1.3
  - morpheus-graphql-client >= 0.17.0
  - req                     >= 2.1.0
  - file-embed

data-files:
  - assets/**/*.gql
  - assets/**/*.json

executables:
  morpheus-client-example:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
