name: morpheus-graphql-client
version: 0.11.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql, client
synopsis: Morpheus GraphQL Client
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!

extra-source-files:
  - changelog.md
  - README.md

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - megaparsec            >= 7.0.0     && <  9.0.0
  - aeson                 >= 1.4.4.0   && <= 1.6
  - containers            >= 0.4.2.1   && <  0.7
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - transformers          >= 0.3.0.0   && <  0.6
  - scientific            >= 0.3.6.2   && <  0.4
  - vector                >= 0.12.0.1  && <  0.13
  - mtl                   >= 2.0       && <= 2.3
  - morpheus-graphql      >= 0.11.0
  - template-haskell      >= 2.0       && <= 2.16

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.Client
  ghc-options: -Wall