name: morpheus-graphql-client
version: 0.16.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql, client
synopsis: Morpheus GraphQL Client
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!

extra-source-files:
  - changelog.md
  - README.md

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - aeson                 >= 1.4.4.0   && <= 1.6
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - morpheus-graphql-core >= 0.15.0    && <  0.16.0
  - template-haskell      >= 2.0       && <= 3.0
  - transformers          >= 0.3.0.0   && <  1.0
  - mtl                   >= 2.0       && <= 3.0
  - relude                >= 0.3.0

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.Client
  ghc-options: -Wall
    -XNoImplicitPrelude

tests:
  morpheus-client-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - morpheus-graphql-client
      - tasty
      - tasty-hunit
      - aeson
      - directory >= 1.0
