name: morpheus-graphql-client
version: 0.19.3
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql, client
synopsis: Morpheus GraphQL Client
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!
extra-source-files:
  - README.md
  - changelog.md
data-files:
  - test/**/*.gql
  - test/**/*.json
dependencies:
  - aeson                      >=  1.4.4   &&  <  3.0.0
  - base                       >=  4.7.0   &&  <  5.0.0
  - bytestring                 >=  0.10.4  &&  <  0.12.0
  - morpheus-graphql-code-gen  >=  0.19.0  &&  <  0.20.0
  - morpheus-graphql-core      >=  0.19.0  &&  <  0.20.0
  - mtl                        >=  2.0.0   &&  <  3.0.0
  - relude                     >=  0.3.0   &&  <  2.0.0
  - text                       >=  1.2.3   &&  <  1.3.0
  - template-haskell           >=  2.0.0   &&  <  3.0.0
  - transformers               >=  0.3.0   &&  <  0.6.0
  - unordered-containers       >=  0.2.8   &&  <  0.3.0
library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.Client
  ghc-options: "-Wall"
tests:
  morpheus-graphql-client-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: "-Wall"
    dependencies:
      - aeson                    >=  1.4.4  &&  <  3.0.0
      - directory                >=  1.0.0  &&  <  2.0.0
      - morpheus-graphql-client
      - tasty                    >=  0.1.0  &&  <  1.5.0
      - tasty-hunit              >=  0.1.0  &&  <  1.0.0
      - file-embed
