query {
  character {
    ... on Character @Turbo @Speed {
      __typename
      name
    }
    ... on Deity {
      __typename
      name
    }
    ... on Hero @Turbo {
      __typename
      name
      hobby
    }
  }
}
