{
    user {name,,,address}

    user {name, ,address}

    user {
        name,
        address
    }

    user {
        name,address
    }

    user {
        name, address
    }

    user {
        name ,address
    }
}
