{
    user {name,,,email}

    user {name, ,email}

    user {name , email , }

    user {
        name,
        email
    }

    user {
        name,email
    }

    user {
        name, email
    }

    user {
        name ,email
    }
}
