interface Character {
  name: String!
}

interface Supernatural {
  power: String!
}

type Hero implements Character {
  name: String!
  hobby: String!
}

type Deity implements Character & Supernatural {
  name: String!
  power: String!
}

type Query {
  character: [Character!]!
}
