name: morpheus-graphql
version: 0.0.1
github: "nalchevanidze/morpheus-graphql"
license: BSD3
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: "d.nalchevanidze@gmail.com"
copyright: "(c) 2019 Daviti Nalchevanidze"

description: Build GraphQL APIs with your favourite functional language!

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers >= 0.4.2.1 && < 0.7
  - unordered-containers
  - split
  - text
  - attoparsec
  - mtl
  - transformers
  - scientific
  - vector


library:
  source-dirs: src
  ghc-options:
      -Wall
