name: morpheus-graphql
version: 0.0.1
github: "nalchevanidze/morpheus-graphql"
license: BSD3
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: "d.nalchevanidze@gmail.com"
copyright: "(c) 2019 Daviti Nalchevanidze"

description: Build GraphQL APIs with your favourite functional language!

dependencies:
  - base                  >= 4.7 && < 5
  - attoparsec            >= 0.13.2.2 && < 0.14
  - aeson                 >= 1.0  &&  <= 1.4.2.0
  - bytestring            >= 0.10.4 && < 0.11
  - text                  >= 1.2.3.0 && < 1.3
  - containers            >= 0.4.2.1 && < 0.7
  - unordered-containers  >= 0.2.8.0  && < 0.3
  - transformers          >= 0.3.0.0 && < 0.6
  - scientific            >= 0.3.6.2  && < 0.4
  - vector                >= 0.12.0.1 && < 0.13
  - mtl                   >= 2.0 && <= 2.2.2

library:
  source-dirs: src
  exposed-modules:
      -  Data.Morpheus
      -  Data.Morpheus.Kind
      -  Data.Morpheus.Types
  ghc-options:
      -Wall
