name: morpheus-graphql
version: 0.0.1
github: "nalchevanidze/morpheus-graphql"
license: BSD3
author: "Davit Nalchevanidze"
maintainer: "d.nalchevanidze@gmail.com"
copyright: "2018 Author name here"

description: Build GraphQL APIs with your favourite functional language!

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers >= 0.4.2.1 && < 0.7
  - unordered-containers
  - split
  - text
  - attoparsec
  - mtl
  - transformers
  - scientific

library:
  source-dirs: src
  ghc-options:
      -fwarn-dodgy-exports
      -fwarn-dodgy-imports
      -fwarn-unused-imports
      -fwarn-duplicate-exports
      -fwarn-missing-fields
      -fwarn-missing-methods
      -fwarn-missing-signatures
      -fwarn-overlapping-patterns
      -fwarn-wrong-do-bind
      -fwarn-unused-matches
      -Werror
