type Query {
  deity(name: String! = "Morpheus"): Deity!
}

type Subscription {
  newDeity: Deity!
}

type Mutation {
  createDeity(name: String!, power: String): Deity!
}

type Deity {
  name: String!
  power: String
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
