name: morpheus-graphql-tests
version: 0.28.2
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql, test
synopsis: Morpheus GraphQL Test
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
description: test utils for morpheus graphql
dependencies:
- aeson                 >=  1.4.4   &&  <  3.0.0
- base                  >=  4.7.0   &&  <  5.0.0
- bytestring            >=  0.10.4  &&  <  1.0.0
- directory             >=  1.0.0   &&  <  2.0.0
- relude                >=  0.3.0   &&  <  2.0.0
- tasty                 >=  0.1.0   &&  <  2.0.0
- tasty-hunit           >=  0.1.0   &&  <  1.0.0
- text                  >=  1.2.3   &&  <  3.0.0
- unordered-containers  >=  0.2.8   &&  <  1.0.0
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Test.Morpheus
