name: morpheus-graphql-tests
version: 0.19.2
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql, test
synopsis: Morpheus GraphQL Test
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
dependencies:
  - aeson                 >=  1.4.4.0  &&  <  3
  - base                  >=  4.7      &&  <  5
  - bytestring            >=  0.10.4   &&  <  0.11
  - directory             >=  1.0      &&  <  2.0
  - relude                >=  0.3.0    &&  <  2.0
  - text                  >=  1.2.3.0  &&  <  1.3
  - tasty                 >=  0.1      &&  <  1.5
  - tasty-hunit           >=  0.1      &&  <  1.0
  - unordered-containers  >=  0.2.8.0  &&  <  0.3
library:
  source-dirs: src
  exposed-modules:
    - Test.Morpheus
  ghc-options: '-Wall'
