{
  object: showMonster(monster: { Hydra: { name: "someName", age: 12 } })
  record: showMonster(monster: { Cerberus: { name: "someName" } })
  enum: showMonster(monster: { UnidentifiedMonster: { _: Empty } })
}
