name: morpheus-graphql-app
version: 0.19.0
github: nalchevanidze/morpheus-graphql-app
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: Morpheus GraphQL App
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!
extra-source-files:
  - README.md
  - changelog.md
data-files:
  - test/**/*.gql
  - test/**/*.json
dependencies:
  - aeson                  >=  1.4.4.0   &&  <  3
  - base                   >=  4.7       &&  <  5
  - bytestring             >=  0.10.4    &&  <  0.11
  - containers             >=  0.4.2.1   &&  <  0.7
  - hashable               >=  1.0.0     &&  <  2.0
  - megaparsec             >=  7.0.0     &&  <  10.0.0
  - mtl                    >=  2.0       &&  <  3.0
  - morpheus-graphql-core  >=  0.19.0    &&  <  0.20.0
  - relude                 >=  0.3.0     &&  <  2.0
  - scientific             >=  0.3.6.2   &&  <  0.4
  - text                   >=  1.2.3.0   &&  <  1.3
  - transformers           >=  0.3       &&  <  0.6
  - template-haskell       >=  2.0       &&  <  3.0
  - th-lift-instances      >=  0.1.1     &&  <  0.3
  - unordered-containers   >=  0.2.8.0   &&  <  0.3
  - vector                 >=  0.12.0.1  &&  <  0.13
library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.App
    - Data.Morpheus.App.Internal.Resolving
    - Data.Morpheus.App.NamedResolvers
    - Data.Morpheus.Types.GQLWrapper
  ghc-options: '-Wall'
tests:
  morpheus-graphql-app-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: '-Wall'
    dependencies:
      - aeson                   >=  1.4.4.0  &&  <  3
      - directory               >=  1.0      &&  <  2.0
      - morpheus-graphql-app
      - morpheus-graphql-tests  >=  0.19.0   &&  <  0.20.0
      - morpheus-graphql-core   >=  0.19.0   &&  <  0.20.0
      - relude                  >=  0.3.0    &&  <  2.0
      - tasty                   >=  0.1      &&  <  1.5
      - tasty-hunit             >=  0.1      &&  <  1.0
