# introspect directives
query Get__Type {
  __schema {
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment InputValue on __InputValue {
  name
  type {
    ...TypeRef
  }
  # defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
