"""
type Description: TestEnum

some random enums for test
"""
enum TestEnum {
  """
  enumValue Description: EnumA
  """
  EnumA
  EnumB
  """
  enumValue Description: EnumC
  """
  EnumC
}

input NestedInputObject {
  fieldTestID: ID!
}

input TestInputObject {
  fieldTestScalar: TestScalar!
  fieldNestedInputObject: [NestedInputObject]!
}

"""
type Description: Coordinates

some random text
"""
input Coordinates {
  """
  inputValue Description: latitude
  """
  latitude: TestScalar!
  """
  inputValue Description: longitude
  some random inputValue details
  """
  longitude: Int!
}

"""
type Description:

  Address
"""
type Address {
  """
  field Description: city
  """
  city: String!
  street(
    """
    argument Description: inputObject
    """
    argInputObject: TestInputObject!
    argMaybeString: String
  ): [[[[String!]!]!]]
  houseNumber: Int!
}

"""
type Description: TestUnion

some random text for union type
"""
union TestUnion = User | Address

"""
User

MultilineDescription

Test
"""
type User {
  """
  field description: name
  """
  name: String!
  """
  field description: email
  """
  email: String!
  address(coordinates: Coordinates!, comment: String): Address!
  office(zipCode: [Int!], cityID: TestEnum!): Address!
  friend: User
}

type Query {
  user: User!
  testUnion: TestUnion
}

type Mutation {
  createUser(userID: String!, userName: String): User!
}

type Subscription {
  newUser: User!
}
