name: morpheus-graphql-server
version: 0.21.0
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!
extra-source-files:
  - README.md
  - changelog.md
data-files:
  - test/**/*.gql
  - test/**/*.json
dependencies:
  - aeson                  >=  1.4.4     &&  <  3.0.0
  - base                   >=  4.7.0     &&  <  5.0.0
  - bytestring             >=  0.10.4    &&  <  0.12.0
  - containers             >=  0.4.2.1   &&  <  0.7.0
  - mtl                    >=  2.0.0     &&  <  3.0.0
  - morpheus-graphql-core  >=  0.21.0    &&  <  0.22.0
  - morpheus-graphql-app   >=  0.21.0    &&  <  0.22.0
  - relude                 >=  0.3.0     &&  <  2.0.0
  - text                   >=  1.2.3     &&  <  1.3.0
  - transformers           >=  0.3.0     &&  <  0.6.0
  - template-haskell       >=  2.0.0     &&  <  3.0.0
  - unordered-containers   >=  0.2.8     &&  <  0.3.0
  - vector                 >=  0.12.0.1  &&  <  0.13.0
library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.Server
    - Data.Morpheus.Server.Types
  ghc-options: "-Wall"
tests:
  morpheus-graphql-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: "-Wall"
    dependencies:
      - aeson                           >=  1.4.4   &&  <  3.0.0
      - file-embed                      >=  0.0.10  &&  <  1.0.0
      - morpheus-graphql-server
      - morpheus-graphql-tests          >=  0.21.0  &&  <  0.22.0
      - morpheus-graphql-subscriptions  >=  0.21.0  &&  <  0.22.0
      - tasty                           >=  0.1.0   &&  <  1.5.0
      - tasty-hunit                     >=  0.1.0   &&  <  1.0.0
