name: morpheus-graphql-examples-scotty
version: 0.28.2
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: examples
copyright: (c) 2019 Daviti Nalchevanidze
description: examples of GraphQL APIs
dependencies:
- aeson                           >=  1.4.4     &&  <   3.0.0
- base                            >=  4.7.0     &&  <   5.0.0
- bytestring                      >=  0.10.4    &&  <   0.15.0
- containers                      >=  0.4.2.1   &&  <=  0.7
- extra                           >=  1.0.0     &&  <   2.0.0
- http-types                      >=  0.5       &&  <   1.0
- morpheus-graphql                >=  0.28.0    &&  <   0.29.0
- morpheus-graphql-app            >=  0.28.0    &&  <   0.29.0
- morpheus-graphql-core           >=  0.28.0    &&  <   0.29.0
- morpheus-graphql-subscriptions  >=  0.28.0    &&  <   0.29.0
- mtl                             >=  2.0.0     &&  <   3.0.0
- scotty                          >=  0.6.0     &&  <   1.0
- stm                             >=  2.1       &&  <   3.0
- text                            >=  1.2.3     &&  <   3.0.0
- transformers                    >=  0.3.0     &&  <   0.7.0
- wai-websockets                  >=  1.0.0     &&  <   4.0
- warp                            >=  1.0.0     &&  <   4.0
- websockets                      >=  0.12.6.0  &&  <   1.0.0
executables:
  scotty-server:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
