name: morpheus-graphql
version: 0.19.3
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: d.nalchevanidze@gmail.com
homepage: https://morpheusgraphql.com
copyright: (c) 2019 Daviti Nalchevanidze
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!
extra-source-files:
  - README.md
  - changelog.md
data-files:
  - test/**/*.gql
  - test/**/*.json
dependencies:
  - aeson                      >=  1.4.4.0   &&  <  3
  - base                       >=  4.7       &&  <  5
  - bytestring                 >=  0.10.4    &&  <  0.11
  - containers                 >=  0.4.2.1   &&  <  0.7
  - mtl                        >=  2.0       &&  <  3.0
  - morpheus-graphql-code-gen  >=  0.19.0    &&  <  0.20.0
  - morpheus-graphql-core      >=  0.19.0    &&  <  0.20.0
  - morpheus-graphql-app       >=  0.19.0    &&  <  0.20.0
  - relude                     >=  0.3.0     &&  <  2.0
  - text                       >=  1.2.3.0   &&  <  1.3
  - transformers               >=  0.3       &&  <  0.6
  - template-haskell           >=  2.0       &&  <  3.0
  - unordered-containers       >=  0.2.8.0   &&  <  0.3
  - vector                     >=  0.12.0.1  &&  <  0.13
library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus
    - Data.Morpheus.Document
    - Data.Morpheus.Kind
    - Data.Morpheus.NamedResolvers
    - Data.Morpheus.Server
    - Data.Morpheus.Types
  ghc-options: '-Wall'
tests:
  morpheus-graphql-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: '-Wall'
    dependencies:
      - aeson                           >=  1.4.4.0  &&  <  3
      - morpheus-graphql
      - morpheus-graphql-tests          >=  0.19.0   &&  <  0.20.0
      - morpheus-graphql-subscriptions  >=  0.19.0   &&  <  0.20.0
      - tasty                           >=  0.1      &&  <  1.5
      - tasty-hunit                     >=  0.1      &&  <  1.0
