directive @MyDirective on FIELD

type Deity {
  name: String!
  power: [String!]!
  friends: [Deity!]!
}

type Query {
  deity(name: String): Deity!
}

schema {
  query: Query
  mutation: Query
  subscription: Query
}
