"""
An object with an ID.
"""
interface Node {
  """
  ID of the object.
  """
  id: ID!
}

"""
Represents a Git object.
"""
interface GitObject {
  id: ID!
}

"""
Represents a Git reference.
"""
type Ref implements Node {
  id: ID!

  """
  The object the ref points to.
  """
  target: GitObject!
}

type Commit implements GitObject & Node {
  id: ID!

  """
  Authorship details of the commit.
  """
  author: String
}

type Tree implements GitObject & Node {
  """
  A list of tree entries.
  """
  treeName: String

  id: ID!
}

type Query {
  myInterface: GitObject!
}
