enum TestEnum {
  EnumA
  EnumB
  EnumC
}

type Address {
  street: [[[[String!]!]!]]
}

input Coordinates {
  latitude: TestScalar!
  longitude: Int!
}

type User {
  type: String!
  address(coordinates: Coordinates!, type: String): Int!
  friend(id: ID!, cityID: TestEnum): User!
}

union TestUnion = User | Address

scalar TestScalar

type MyQuery {
  user: User!
  testUnion: TestUnion
}

schema {
  query: MyQuery
}
