scalar TestScalar

enum TestEnum {
  EnumA
  EnumB
  EnumC
}

input Coordinates {
  latitude: TestScalar!
  longitude: Int!
}

type Address {
  street: [[[[String!]!]!]]
  score: Float!
}

type User {
  type: String!
  address(coordinates: Coordinates!, type: String): Int!
  friend(id: ID!, cityID: TestEnum): User!
}

union TestUnion = User | Address

type MyQuery {
  user: User!
  testUnion: TestUnion
}

type MyMutation {
  newUser: User!
}

schema {
  query: MyQuery
  mutation: MyMutation
}
