name: morpheus-graphql-examples-yesod-pubsub
version: 0.28.1
github: nalchevanidze/morpheus-graphql
license: BSD3
author: Josh Brown
category: web, graphql
synopsis: examples of external pub-sub
copyright: 2021 ROPWARE
description: examples of a GraphQL server using postgresql/rabbitmq as a pusub
extra-source-files:
- ChangeLog.md
- README.md
dependencies:
- base                            >=  4.7.0     &&  <  5.0.0
- blaze-html                      >=  0.2       &&  <  1.0.0
- bytestring                      >=  0.10.4    &&  <  1.0.0
- extra                           >=  1.0.0     &&  <  2.0.0
- hashable                        >=  1.0.0     &&  <  2.0.0
- morpheus-graphql                >=  0.28.0    &&  <  0.29.0
- morpheus-graphql-core           >=  0.28.0    &&  <  0.29.0
- morpheus-graphql-server         >=  0.28.0    &&  <  0.29.0
- morpheus-graphql-subscriptions  >=  0.28.0    &&  <  0.29.0
- shakespeare                     >=  1.0       &&  <  3.0.0
- text                            >=  1.2.3     &&  <  3.0.0
- unliftio-core                   >=  0.0.1     &&  <  1.0.0
- wai                             >=  1.0.0     &&  <  4.0.0
- wai-cors                        >=  0.1.0     &&  <  1.0.0
- wai-websockets                  >=  1.0.0     &&  <  4.0.0
- warp                            >=  1.0.0     &&  <  4.0.0
- websockets                      >=  0.12.6.0  &&  <  1.0.0
- yesod                           >=  0.5       &&  <  2.0.0
- yesod-core                      >=  1.0       &&  <  2.0.0
library:
  source-dirs: src
executables:
  yesod-gql-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wdefault
    - -Wmissing-fields
    - -Wwarn
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - morpheus-graphql-examples-yesod-pubsub  >=  0.28.0  &&  <  0.29.0
tests:
  yesod-gql-example-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - morpheus-graphql-examples-yesod-pubsub  >=  0.28.0  &&  <  0.29.0
