name:                morpheus-graphql-examples-yesod-pubsub
version:             0.1.0.0
github:              "nalchevanidze/morpheus-graphql"
license:             BSD3
author:              "Josh Brown"
copyright:           "2021 ROPWARE"
category: web, graphql
synopsis: examples of external pub-sub
description: examples of a GraphQL server using postgresql/rabbitmq as a pusub

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- text
- extra
- hashable
- bytestring
- yesod
- yesod-core
- blaze-html
- shakespeare
- morpheus-graphql
- morpheus-graphql-server
- morpheus-graphql-core
- morpheus-graphql-subscriptions
- warp
- wai
- wai-cors
- wai-websockets
- websockets
- unliftio-core

library:
  source-dirs: src

executables:
  yesod-gql-example:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wdefault
    - -Wwarn
    - -Wmissing-fields
    - -with-rtsopts=-N
    dependencies:
    - morpheus-graphql-examples-yesod-pubsub

tests:
  yesod-gql-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morpheus-graphql-examples-yesod-pubsub
