name: morpheus-graphql-examples-scotty-fraxl
version: 0.28.1
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: examples
copyright: (c) 2019 Daviti Nalchevanidze
description: Fraxl example of GraphQL APIs
dependencies:
- base              >=  4.7.0    &&  <   5.0.0
- containers        >=  0.4.2.1  &&  <=  1.0.0
- fraxl             >=  0.1      &&  <   1.0.0
- morpheus-graphql  >=  0.28.0   &&  <   0.29.0
- mtl               >=  2.0.0    &&  <   3.0.0
- scotty            >=  0.6.0    &&  <   1.0.0
- text              >=  1.2.3    &&  <   3.0.0
executables:
  scotty-server-fraxl:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
