name: examples
version: 0.1.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: examples
copyright: "(c) 2019 Daviti Nalchevanidze"
description: examples of GraphQL APIs

dependencies:
  - base                  >= 4.7       && <  5
  - aeson                 >= 1.4.4.0   && <= 1.6
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - containers            >= 0.4.2.1   && <  0.7
  - mtl                   >= 2.0       && <= 2.3
  - websockets            >= 0.11.0    &&  <= 0.13
  - morpheus-graphql      >= 0.11.0
  - scotty
  - wai
  - warp
  - req
  - wai-websockets        >= 1.0       &&  <= 3.5
  - transformers
  - extra
  - http-types
  - stm
  - servant
  - servant-server

executables:
  api:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
