name: examples
version: 0.1.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"

description: examples of GraphQL APIs

dependencies:
  - base                >= 4.7   &&    < 5
  - morpheus-graphql
  - scotty
  - aeson
  - bytestring
  - mtl
  - text
  - wai
  - warp
  - wai-websockets        >= 1.0       &&  <= 3.5
  - websockets            >= 0.11.0    &&  <= 0.13
  - containers            >= 0.4.2.1   &&  <  0.7

executables:
  api:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
