name: morpheus-graphql-examples-client
version: 0.28.1
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: examples
copyright: (c) 2019 Daviti Nalchevanidze
description: examples of GraphQL APIs
data-files:
- assets/**/*.gql
- assets/**/*.json
dependencies:
- base                     >=  4.7.0   &&  <  5.0.0
- bytestring               >=  0.10.4  &&  <  1.0.0
- file-embed               >=  0.0.10  &&  <  1.0.0
- morpheus-graphql-client  >=  0.28.0  &&  <  0.29.0
- req                      >=  3.0.0   &&  <  4.0.0
- text                     >=  1.2.3   &&  <  3.0.0
executables:
  morpheus-client-example:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
