{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE TypeFamilies  #-}

-- generated by 'Morpheus' CLI
module Schema where

import           Data.Morpheus.Kind  (ENUM, INPUT_OBJECT, OBJECT, SCALAR, UNION)
import           Data.Morpheus.Types (GQLType (..), ResM)
import           GHC.Generics        (Generic)

---- GQL Query -------------------------------
data Query = Query
  { deity     :: ArgDeity -> ResM Deity
  , character :: ArgCharacter -> ResM Character
  } deriving (Generic)

data ArgDeity = ArgDeity
  { name      :: Maybe [Maybe [Maybe [[Maybe [String]]]]]
  , mythology :: Maybe String
  } deriving (Generic)

data ArgCharacter = ArgCharacter
  { characterID :: String
  , age         :: Maybe Int
  } deriving (Generic)

instance GQLType Query where
  type KIND Query = OBJECT

resolveQuery :: ResM Query
resolveQuery = return Query {}

---- GQL Mutation -------------------------------
data Mutation = Mutation
  { createDeity     :: ArgCreateDeity -> ResM Deity
  , createCharacter :: ArgCreateCharacter -> ResM Character
  } deriving (Generic)

data ArgCreateDeity = ArgCreateDeity
  { deityName      :: Maybe [Maybe [Maybe [[Maybe [String]]]]]
  , deityMythology :: Maybe String
  } deriving (Generic)

data ArgCreateCharacter = ArgCreateCharacter
  { charRealm :: Realm
  , charMutID :: String
  } deriving (Generic)

instance GQLType Mutation where
  type KIND Mutation = OBJECT

resolveMutation :: ResM Mutation
resolveMutation = return Mutation {}

---- GQL City -------------------------------
data City
  = Athens
  | Ithaca
  | Sparta
  | Troy
  deriving (Generic)

instance GQLType City where
  type KIND City = ENUM

resolveCity :: ResM City
resolveCity = return Athens

---- GQL Power -------------------------------
data Power =
  Power Int
        Int

instance GQLType Power where
  type KIND Power = SCALAR

resolvePower :: ResM Power
resolvePower = return $ Power 0 0

---- GQL Realm -------------------------------
data Realm = Realm
  { owner :: String
  , place :: Maybe Int
  } deriving (Generic)

instance GQLType Realm where
  type KIND Realm = INPUT_OBJECT

---- GQL Deity -------------------------------
data Deity = Deity
  { fullName :: () -> ResM String
  , power    :: () -> ResM (Maybe String)
  } deriving (Generic)

instance GQLType Deity where
  type KIND Deity = OBJECT

resolveDeity :: ResM Deity
resolveDeity = return Deity {}

---- GQL Creature -------------------------------
data Creature = Creature
  { creatureName :: () -> ResM String
  , abilities    :: () -> ResM (Maybe String)
  } deriving (Generic)

instance GQLType Creature where
  type KIND Creature = OBJECT

resolveCreature :: ResM Creature
resolveCreature = return Creature {}

---- GQL Human -------------------------------
data Human = Human
  { humanName  :: () -> ResM String
  , profession :: () -> ResM (Maybe String)
  } deriving (Generic)

instance GQLType Human where
  type KIND Human = OBJECT

resolveHuman :: ResM Human
resolveHuman = return Human {}

---- GQL Character -------------------------------
data Character
  = Character_CREATURE Creature
  | Character_DEITY Deity
  | Character_HUMAN Human
  deriving (Generic)

instance GQLType Character where
  type KIND Character = UNION

resolveCharacter :: ResM Character
resolveCharacter = Character_CREATURE <$> resolveCreature
