type Query {
  deity (name: [[[[[String!]]!]]],
  mythology: String): Character
}

union Character = Creature | Deity  | Human

type Deity {
  fullName: String!
  power: String
}

type Creature {
  creatureName: String!
  abilities: String
}

type Human {
  humanName: String!
  profession: String
}

enum City {
    Athens
    Ithaca
    Sparta Troy
}

scalar Power