query TestFragments($x: Boolean! = false, $y: Boolean! = false) {
  user {
    name
    ...UserName @skip(if: $x)
    ... on User @include(if: $y) {
      name2: name
    }
  }
}

fragment UserName on User {
  name1: name
}
