directive @DirectiveA on INPUT_OBJECT

directive @DirectiveB on SCALAR

directive @DirectiveC on ENUM

directive @DirectiveD on INPUT_FIELD_DEFINITION

scalar MyScalar @DirectiveA

enum TestEnum @DirectiveB {
  EnumA @DirectiveC
  EnumB
}

input Input1 @deprecated {
  field1: ID @include(if: true)
  field2: String
}

type Query @deprecated {
  field(a1: Int @DirectiveD): Int @include(if: true)
}
