name: morpheus-graphql-examples-scotty-freer
version: 0.1.0.0
github: "githubuser/morpheus-graphql-examples-scotty-freer-simple"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"
description: example of graphql apis with scotty and freer-simple

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - file-embed
  - freer-simple
  - morpheus-graphql
  - scotty
  - text
  - transformers
  - wai
  - warp

executables:
  scotty-freer-server:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
