{
  user {
    bla: email
    email
    bla: email
    address(coordinates: { latitude: "", longitude: 1 }) {
      city
      bla: city
    }
  }
  user {
    address(coordinates: { latitude: "", longitude: 1 }) {
      bla: houseNumber
    }
    bla: email
  }
}
