query ValidMap {
  f1: testMap(value: []) {
    ...Entry
  }
  f2: testMap(
    value: [
      { _0: "zeus", _1: 3468 }
      { _0: "morpheus", _1: 4236 }
      { _0: "cronos", _1: 547 }
    ]
  ) {
    ...Entry
  }
}

fragment Entry on PairTextInt {
  _0
  _1
}
