query InvalidTuple {
  f1: testMap(value: [])
  f2: testMap(value: {})
  f3: testMap(value: { _0: 2 })
  f4: testMap(value: { _0: "235" })
  f4: testMap(value: { _0: "235", _1: "235235" })
  f4: testMap(value: { _0: "235", _1: false })
  f5: testMap(value: { _0: "34", _1: 2353 })
}
