name: morpheus-graphql-core
version: 0.11.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL Core
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"
license-file: LICENSE
description: Build GraphQL APIs with your favourite functional language!

extra-source-files:
  - changelog.md
  - README.md

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - megaparsec            >= 7.0.0     && <  9.0.0
  - aeson                 >= 1.4.4.0   && <= 1.6
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - transformers          >= 0.3.0.0   && <  0.6
  - scientific            >= 0.3.6.2   && <  0.4
  - vector                >= 0.12.0.1  && <  0.13
  - template-haskell      >= 2.0       && <= 2.16
  - th-lift-instances     >= 0.1.1     && <= 0.2.0

library:
  source-dirs: src
  exposed-modules:
    - Data.Morpheus.Core
    - Data.Morpheus.QuasiQuoter
    - Data.Morpheus.Error

    - Data.Morpheus.Internal.TH
    - Data.Morpheus.Internal.Utils
    - Data.Morpheus.Types.Internal.Operation
    - Data.Morpheus.Types.Internal.AST
    - Data.Morpheus.Types.IO
    - Data.Morpheus.Types.Internal.Resolving

  ghc-options: -Wall

