name: morpheus-graphql-cli
version: 0.1.0
github: "morpheusgraphql/morpheus-graphql"
license: BSD3
author: "Daviti Nalchevanidze"
category: web, graphql, cli
synopsis: Morpheus GraphQL CLI
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"

description: code generator for Morpheus GraphQL

extra-source-files:
  - changelog.md
  - README.md

dependencies:
  - base                  >= 4.7       && <  5
  - morpheus-graphql-core >= 0.17.0    && <  0.18.0
  - morpheus-graphql      >= 0.17.0    && <  0.18.0
  - optparse-applicative  >= 0.12      && <  0.17
  - filepath              >= 1.1       && <  1.5
  - text                  >= 1.2.3.0   && <  1.3
  - bytestring            >= 0.10.4    && <  0.11
  - prettyprinter         >= 1.5.1     && <  2.0
  - unordered-containers  >= 0.2.8.0   && <  0.3

executables:
  morpheus:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
