enum TestEnum {
  EnumA
  EnumB
  EnumC
}

input Input1 {
  field1: ID! = EnumA
  field2: String! = EnumA
  field3: TestEnum = UnknownEnum
  field4: TestEnum! = 1
  field5: TestEnum = "some text"
}

input Input2 {
  objectField: Input1 = { field1: true, field2: true, field3: tre }
  fieldString: String
}

type Query {
  field: Int
}
