name: morpheus-graphql-morpheus-graphql-examples-servant
version: 0.1.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: examples
copyright: "(c) 2019 Daviti Nalchevanidze"
description: examples of GraphQL APIs

dependencies:
  - base                    >= 4.7       && <  5
  - bytestring              >= 0.10.4    && <  0.11
  - text                    >= 1.2.3.0   && <  1.3
  - mtl                     >= 2.0       && <= 2.3
  - morpheus-graphql        >= 0.12.0
  - warp
  - servant-server
  - http-media

data-files:
  - assets/**/*.html

executables:
  servant-server:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
