query($isTrue: Boolean!, $isFalse: Boolean!) {
  a: simple {
    value: name @include(if: $isTrue)
    skip: name @skip(if: $isTrue)
  }
  b: simple {
    skip: name @include(if: $isFalse)
    value: name @skip(if: $isFalse)
  }
}
