title: Morpheus GraphQL
email: your-email@example.com
description: Haskell GraphQL library, Build GraphQL APIs with your favourite functional language!
baseurl: ""
url: "https://morpheusgraphql.com"
twitter_username: jekyllrb
github_username: jekyll

markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
