# for Input Union

input Cat {
  catName: String!
}

input Dog {
  dogName: String!
}

input Bird {
  birdName: String!
}

# Main APi

enum CityID {
  Paris
  BLN
  HH
}

input Coordinates {
  latitude: Euro!
  longitude: [[[UniqueID!]!]]!
}

input UniqueID {
  uid: String!
}

type Address {
  city: String!
  street: String!
  houseNumber: Int!
}

type User {
  name: String!
  email: String!
  address(coordinates: Coordinates!, comment: String): Address!
  office(zipCode: [[[ID!]]!], cityID: CityID!): Address!
  myUnion: MyUnion!
  home: CityID!
}

union MyUnion = User | Address

type Query {
  user: User!
  wrappedA1: AIntText!
  setAnimal(animal: Animal): String!
  wrappedA2: AText!
  integerSet: SetInt!
  textIntMap: MapTextInt!
}

type Mutation {
  createUser: User!
  createAddress: Address!
}

type Subscription {
  newAddress: Address!
  newUser: User!
}
