# for Input Union

input Cat {
  name: String!
}

input Dog {
  name: String!
}

input Bird {
  name: String!
}

# Main APi

enum CityID {
  Paris
  BLN @testDirective(testName:"")
  HH
}

input Coordinates {
  latitude: Euro! @testDirective(testName:"")
  longitude: [[[UniqueID!]!]]!
}

input UniqueID {
  type: String,
  id: String!
}

type Address {
  city: String!  @deprecated(testName:"",testName2: 123)
  street: String!
  houseNumber: Int!
}

type User {
  name: String!
  email: String!
  address(coordinates: Coordinates!, comment: String): Address!
  home: CityID!
  office(zipCode: [[[ID!]]!], id: CityID!): Address
  entity: MyUnion
}

union MyUnion = User | Address

type Query {
  user: User!
  animal(animal: Animal): String!
  wrapped1(type: UniqueID): AIntText!
  wrapped2: AText!
  set: SetInt!
  map: MapTextInt!
}

type Mutation {
  createUser: User!
  createAddress: Address!
}

type Subscription {
  newAddress: Address!
  newUser: User!
}
