name: morpheus-graphql-examples-scotty-haxl
version: 0.28.1
github: nalchevanidze/morpheus-graphql
license: MIT
author: Daviti Nalchevanidze
category: web, graphql
synopsis: examples
copyright: (c) 2019 Daviti Nalchevanidze
description: examples of GraphQL APIs
dependencies:
- base                  >=  4.7.0    &&  <   5.0.0
- containers            >=  0.4.2.1  &&  <=  0.7
- hashable              >=  1.0.0    &&  <   2.0.0
- haxl                  >=  0.1.0    &&  <   3.0
- morpheus-graphql      >=  0.28.0   &&  <   0.29.0
- morpheus-graphql-app  >=  0.28.0   &&  <   0.29.0
- mtl                   >=  2.0.0    &&  <   3.0.0
- scotty                >=  0.6.0    &&  <   1.0
- text                  >=  1.2.3    &&  <   3.0.0
executables:
  scotty-server-haxl:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
