name: morpheus-graphql-examples-scotty-haxl
version: 0.1.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: examples
copyright: "(c) 2019 Daviti Nalchevanidze"
description: examples of GraphQL APIs

dependencies:
  - base                            >= 4.7       && <  5
  - mtl                             >= 2.0
  - text                            >= 1.2.3.0
  - containers                      >= 0.4.2.1
  - morpheus-graphql
  - morpheus-graphql-app
  - scotty
  - haxl
  - hashable

executables:
  scotty-server-haxl:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
