name: Publish Binaries
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetOs: linux
            execName: morpheus
          - os: macOS-latest
            targetOs: mac-os
            execName: morpheus
          - os: windows-latest
            targetOs: windows
            execName: morpheus.exe
    name: Build binary for ${{ matrix.targetOs }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: ./.github/actions/setup-hs
        with:
          ghc: latest

      - name: build binary
        run: stack build morpheus-graphql-code-gen

      - name: prepare upload
        run: |
          mkdir out
          cp $(stack exec which morpheus) ./out/${{ matrix.fileName }}
          7z a -l ./morpheus.zip ./out

      - name: upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # upload_url: ${{ github.event.release.upload_url }}
          upload_url: "https://uploads.github.com/repos/morpheusgraphql/morpheus-graphql/releases/80705605/assets{?name,label}"
          asset_path: morpheus.zip
          asset_name: morpheus-${{ matrix.targetOs }}
          asset_content_type: application/octet-stream
