name: Publish Binaries
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetOs: Linux
          - os: macOS-latest
            targetOs: macOS
          - os: ubuntu-latest
            targetOs: Windows
    name: Build binary for ${{ matrix.targetOs }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: ./.github/actions/setup-hs
        with:
          ghc: latest

      - name: build binary
        run: stack build morpheus-graphql-code-gen

      - name: prepare binary
        run: |
          cp $(stack exec which morpheus) ./morpheus
          ls

      - name: upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # upload_url: ${{ github.event.release.upload_url }}
          upload_url: https://github.com/morpheusgraphql/morpheus-graphql/releases/0.24.1
          asset_path: morpheus
          asset_name: morpheus-${{ matrix.targetOs }}
          asset_content_type: application/octet-stream
