name: Publish Binaries
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetOs: Linux
          - os: macOS-latest
            targetOs: macOS
          - os: ubuntu-latest
            targetOs: Windows
    name: Build binary for ${{ matrix.targetOs }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1.2
      - run: stack install morpheus-graphql-code-gen
      - run: cp ./local
      - name: Prepare upload
        run: cp ~/.local/bin/morpheus ~/morpheus-${{ matrix.os }}

      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: ormolu.zip
      #     asset_name: ormolu-${{ matrix.targetOs }}.zip
      #     asset_content_type: application/zip
