name: Publish Binaries
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetOs: linux
          - os: macOS-latest
            targetOs: mac-os
          - os: ubuntu-latest
            targetOs: windows
    name: Build binary for ${{ matrix.targetOs }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: ./.github/actions/setup-hs
        with:
          ghc: latest

      - name: build binary
        run: stack build morpheus-graphql-code-gen

      - name: Prepare upload
        run: 7z a -l ./morpheus.zip .

      - name: prepare binary
        run: |
          cp $(stack exec which morpheus) ./morpheus
          ls

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # upload_url: ${{ github.event.release.upload_url }}
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: morpheus
          asset_name: morpheus-${{ matrix.targetOs }}
          asset_content_type: application/octet-stream
