name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare OS
        uses: actions/checkout@v1
      - name: Setup stack
        uses: mstksg/setup-stack@v1
      - name: prepare
        run: |
          stack sdist
      - name: upload
        run: |
          stack upload morpheus-graphql-core
          stack upload morpheus-graphql-client
          stack upload .
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
