name: Tags

on:
  pull_request:
    types: [ labeled, closed ]

jobs:
  publish-releases:
    if: ${{ github.event.label.name == 'pr/release' }}
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'HALLO FROM TAGS 2'
