name: Upload Artifacts
on: push

# thanks to:  https://github.com/tweag/ormolu/blob/master/.github/workflows/binaries.yml

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            executable: morpheus
          - os: macOS-latest
            target: mac-os
            executable: morpheus
          - os: windows-latest
            target: windows
            executable: morpheus.exe
    name: Upload Artifacts for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: ./.github/actions/setup-hs
        with:
          ghc: latest

      - name: Build Artifacts
        run: stack build morpheus-graphql-code-gen
        shell: bash

      - name: Prepare Artifacts
        run: |
          mkdir out
          cd ./out
          cp $(stack exec which morpheus) ./${{ matrix.executable }}
          7z a ../morpheus.zip .
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # upload_url: ${{ github.event.release.upload_url }}
          upload_url: "https://uploads.github.com/repos/morpheusgraphql/morpheus-graphql/releases/80705605/assets{?name,label}"
          asset_path: morpheus.zip
          asset_name: morpheus-${{ matrix.target }}.zip
          asset_content_type: application/octet-stream
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macOS-latest
            target: mac-os
          - os: windows-latest
            target: windows
    name: Test Binaries
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      # curl -o morpheus.zip -LO https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/morpheus-${{ matrix.target }}.zip
      - name: Download and extract Artifact
        run: |
          curl -o morpheus.zip -LO https://github.com/${{ github.repository }}/releases/download/0.24.1/morpheus-${{ matrix.target }}.zip
          7z e morpheus.zip
      - name: Test CLI Commands
        run: |
          ./morpheus about
          ./morpheus build examples/code-gen
          ./morpheus build examples/code-gen-docs
          ./morpheus check examples/code-gen
          ./morpheus check examples/code-gen-docs
