name: morpheus-graphql-benchmark
version: 0.17.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL Benchmark
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"
license-file: LICENSE
description: Build GraphQL APIs with your favorite functional language!

extra-source-files:
  - changelog.md
  - README.md

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - transformers          >= 0.3.0.0   && <  0.6
  - mtl                   >= 2.0       && <= 3.0
  - relude                >= 0.3.0
  - containers            >= 0.4.2.1   && <  0.7

benchmark:
  morpheus-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -eventlog
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N6
      - -O2
    dependencies:
      - base                  >= 4.7       && <  5
      - morpheus-graphql-core
      - criterion
      - bytestring            >= 0.10.4    && <  0.11
      - graphql               >= 0.11
