type Query {
  deity(name: String): Deity!
}

interface Character {
  name: String
}

interface Supernatural {
  power: [String!]!
}

type Hero implements Character {
  field: String
}

type Deity implements Character & Supernatural {
  name: Int
  power: [String!]
}
